config/routes.rb
Rails.application.routes.draw do
  root 'physicians#index'

  resources :patients
  resources :physicians do
    resources :appointments, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :Patient
  belongs_to :Physician
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :physicians, through: :appointments

  validates :name, presence: true
end

app/models/physician.rb
class Physician < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments

  validates :name, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show]
  before_action :set_doctor
  before_action :set_patients, only: [:new, :create]

  def index
    @appointments = @physician.appointments
  end

  def new
    @patients = Patient.all - @physician.patients
    @appointment = @physician.appointments.new
  end

  def show
    @patient = @appointment.patient.find(params[:id])
    @doctor = @appointment.doctor.find(params[:doctor_id])
  end

  def new
    @patients = Patient.all - @physician.patients
    @appointment = @physician.appointments.new
  end

  def create
    @appointment = @physician.appointments.new(appointment_params)
    
    if @appointment.save
      redirect_to physician_appointments_path
    else
      render :new
    end
  end

  def destroy
    @physician.appointments.find(params[:id]).destroy
    redirect_to physician_appointments_path
  end

  private
    def set_physician
      @physician = Physician.find(params[:physician_id])
    end

    def set_appointment
    @appointment = Appointment.find(params[:id])
    end

    def set_patients
    @patients = (Patient.all - @physician.patients)
    end

    def appointment_params
    params.require(:appointment).permit(:patient_id, :date, :time)
    end
  end
end
  

    

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  
  def index
    @patients = Patient.all
  end

  def show
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    
    if @patient.save
      redirect_to @patient
    else
      render :new 
    end
  end

  def edit
  end

  def update
    if @patient.update(patient_params)
      redirect_to @patient
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_path
  end

  private
    def patient_params
      params.require(:patient).permit(:name, :age, :email)
    end

    def set_patient
      @patient = Patient.find(params[:id])
    end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: [:show, :edit, :update, :destroy]

  def index
    @physicians = Physician.all
  end

  def show
  end

  def new
    @physician = Physician.new 
  end

  def create 
    @physician = Physician.new(physician_params)

    if @physician.save
      redirect_to @physician
    else
      render :new
    end
  end

  def edit
  end

  def update 
    if @physician.update(physician_params)
      redirect_to @physician 
    else
      render :edit
    end
  end

  def destroy
    @physician.destroy
    redirect_to physicians_path
  end

  private 
    def physician_params
      params.require(:physician).permit(:name, :email, :specialty)
    end

    def set_physician
      @physician = Physician.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/appointments/index.html.erb
<h1><%= @physician.name %> Appointments</h1>
<%= link_to 'Add Appointment', new_physician_appointment_path(@physician) %>
<br />
<table class="ui celled table">
  <thead>
    <th>Patient Name</th>
    <th>Patient Age</th>
    <th>Appointment Date</th>
    <th>Appointment Time</th>
    <th>Remove</th>
  </thead>
  <tbody>
    <% @appointments.each do |appt| %>
      <tr>
        <td><%= link_to appt.patient.name, patient_path(appt.patient), class: "ui basic button"%></td>
        <td><%= appt.patient.age %></td>
        <td><%= appt.date.strftime('%a, %b %d, %Y') %></td>
        <td><%= appt.time.strftime("%l:%M %p")  %></td>
        <td><%= button_to 'Cancel', physician_appointment_path(appt.doctor_id, appt.id), method: :delete, class:"ui button red inverted" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/appointments/new.html.erb
<h1>Add Appointment</h1>

<%= form_with(model: [@physician, @appointment], local: true, class: "ui form" ) do |f| %>
  <%= f.label :patient %>
  <%= f.select :patient_id, @patient.collect { |p| [p.name, p.id]} %>
  <br />
  <%= f.label :date %>
  <%= f.date_field :date %>
  <br />
  <%= f.label :time %>
  <%= f.time_field :time %>
  <br />
  <br />
  <%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/appointments/show.html.erb
<h1>Appointment Show</h1>

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <li>
      <%= link_to 'Physicians', physicians_path %>
    </li>
    <li>
      <%= link_to 'Add Physician', new_physician_path %>
    </li>
    <li>
      <%= link_to 'Patients', patients_path %>
    </li>
    <li>
      <%= link_to 'Add Patient', new_patient_path %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorAppt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class="ui container">
    <%= yield %>
  </div>
</body>
</html>

app/views/patients/edit.html.erb
<h1>Edit Patient</h1>

<%= form_for @patient do |p| %>
<%= p.label :name %>
<%= p.text_field :name %><br><br>

<%= p.label :age %>
<%= p.number_field :age %><br><br>

<%= p.label :email %>
<%= p.text_field :email %><br><br>

<%= p.submit %>


<% end %>

app/views/patients/index.html.erb
<h1>Patients</h1>
<ul>
  <% @patients.each do |patient| %>
    <li>
      <%= link_to patient.name, patient %></td>
    </li>
  <% end %>
</ul>

app/views/patients/new.html.erb
<h1>Add Patient</h1>
<%= form_with(model: @patient, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true, placeholder: "Name" %>
  </div>
  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :email, required: true, placeholder: "Age" %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email, required: true, placeholder: "Email" %>
  </div>
  <%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/patients/show.html.erb
<h1><%= @patient.name %></h1>
<hr />
<br />
<%= link_to 'Appointments', physician_appointments_path(@patient), class: "ui primary button inverted" %>
<br />
<br />
<br />
<%= link_to "Delete Patient", @patient , method: :delete, class: "ui red button inverted" %>

app/views/physicians/edit.html.erb
<h1>Edit Physician</h1>

<%= form_for @physican do |p| %>
<%= p.label :name %>
<%= p.text_field :name %><br><br>

<%= p.label :email %>
<%= p.email_field :email %><br><br>

<%= p.label :specialty %>
<%= p.text_field :specialty %><br><br>

<%= p.submit %>


<% end %>

app/views/physicians/index.html.erb
<h1>Physicians</h1>
<ul>
  <% @physicians.each do |physician| %>
    <li>
      <%= link_to physician.name, physician %>
    </li>
  <% end %>
</ul>

app/views/physicians/new.html.erb
<h1>Add Physician</h1>
<%= form_with(model: @physician, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true, placeholder: "Name" %>
  </div>
  <div class="field">
    <%= f.label :specialty %>
    <%= f.text_field :email, required: true, placeholder: "Specialty" %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email, required: true, placeholder: "Email" %>
  </div>
  <%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/physicians/show.html.erb
<h1><%= @physician.name %></h1>
<hr />
<br />
<%= link_to 'Appointments', physician_appointments_path(@physician), class: "ui primary button inverted" %>
<br />
<br />
<br />
<%= link_to "Delete Physician", @physician , method: :delete, class: "ui red button inverted" %>